Extend CLI parameters and Add Github Actions for Docker .
weigertlab/spotiflow pull request #11
Opened 2024-06-28 12:05 UTC by migueLib

## What type of PR is this? (check all applicable)

- [ ] Bug Fix
- [X] Feature
- [ ] Optimization
- [ ] Documentation Update

## Description
- This PR extends the CLI for spotiflow-predict 
- Adds GitHub actions workflow to create a Docker container on release and PR.

## Related issues (if applicable)

- Related Issue #
 
- Closes #
When approved, this PR closes issues #10 #9

2024-06-28 15:24 UTC, AlbertDominguez requested changes

2024-06-28 15:24 UTC, AlbertDominguez commented on Dockerfile
> +LABEL maintainer="Miguel Ibarra"
Could you add myself as a maintainer too?

2024-06-28 15:24 UTC, AlbertDominguez commented on environment.yml
Looks like this is used for building the container. I see a slight problem in that it builds `cpuonly` so users might be a bit confused if they think they can use this `environment.yml` to create a conda environment (which they could of course), but then it wouldn't be cuda-compatible.
Could this (and the `Dockerfile`) be moved to a new directory in the root (e.g. `docker` or `container`) w/o disrupting the nextflow pipeline?

2024-06-28 15:24 UTC, AlbertDominguez commented on Dockerfile
See comment on `environment.yml`

2024-06-28 15:24 UTC, AlbertDominguez commented on README.md
> +Alternatively to installing Spotiflow as command line tool on your operating system, you can also use it directly from our Docker container. To do so, you can use the following command:
```suggestion
Alternatively to installing Spotiflow as command line tool on your operating system, you can also use it directly from our Docker container (thanks to @migueLib for the contribution!). To do so, you can use the following command:
```

2024-06-28 15:24 UTC, AlbertDominguez commented on .github/workflows/docker-publish.yml
> +  push:
the current tag releases are `X.Y.Z` without the leading `v`. Would it work without `v` too? We could also do it not by tag but for release, as done in the other workflows

2024-07-01 11:28 UTC, migueLib commented on environment.yml
Yes, you are absolutely right. It might create some confusion.

I can suggest using a different name for that file, something like docker-env-config.yaml but keeping both on the same directory, as they are now.

2024-07-02 08:54 UTC, AlbertDominguez approved these changes
lgtm!

2024-07-02 20:26 UTC, merged